факториал
js-tasks-ru/jsbasic-20220113_petrzavadski pull request #3
Opened 2022-01-18 10:37 UTC by petrzavadski

Не покидает чувство, что много лишнего

2022-01-18 10:38 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-18 11:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-01-19 01:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-01-19 11:08 UTC, SinimaWath requested changes

2022-01-19 11:08 UTC, SinimaWath commented on 1-module/1-task/index.js
> +return res
Прочитай советы по стилю написания кода из Задачника:  https://learn.javascript.ru/coding-style

И попробуй переписать задачу

2022-01-19 11:08 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return true
Тут тоже попробуй использовать советы из стиля кода

2022-01-19 11:08 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if ((str=='') || (str==null)) return ''
Эту проверку можно упростить до:
```
if (!str) {
  return;
}
```

2022-01-19 11:08 UTC, SinimaWath commented on 1-module/4-task/index.js
> +return false
Давай попробуем переписать без if, а используя логические операторы:
`return condition1 || condition2`

2022-01-20 02:00 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-20 12:39 UTC, SinimaWath requested changes

2022-01-20 12:39 UTC, SinimaWath commented on 1-module/1-task/index.js
> +return res
Давай попробуем тут сделать более читаемые отступы:
```
function factorial(n) {
  if () {
    return ...
  }
  
  let ...
  
  for () {
    ...
  }
  
  return ...
}
```

Отступы - это на самом деле важно :) Правильное разделение кода и блоков, делает код более читаемым

2022-01-20 12:39 UTC, SinimaWath commented on 1-module/4-task/index.js
> +return (str.toLowerCase().includes('1XbeT'.toLowerCase())) || (str.toLowerCase().includes('XXX'.toLowerCase())) || false
Тут нет необходимости в || false.
includes - возвращает true/false:

поэтому можно оставить вот так:
`return str.toLowerCase().includes('1XbeT'.toLowerCase()) || str.toLowerCase().includes('XXX'.toLowerCase())`

2022-01-20 17:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-21 10:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-01-21 11:23 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-22 14:05 UTC, SinimaWath requested changes

2022-01-22 14:05 UTC, SinimaWath commented on 2-module/1-task/index.js
> +return 0;
- Беда с отступами, в  нужно править

```
function fn() {
  let sum = 0;

  for (..) {
    if () {
    }
  }
  
  if () {
  
  }
}
```

2022-01-22 14:05 UTC, SinimaWath commented on 2-module/1-task/index.js
> +return 0;
Также в этой задачи нет необходимости в reduce.

Вместо того, чтобы делать push в sum, просто прибавляй значение

2022-01-22 20:43 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-24 10:08 UTC, SinimaWath approved these changes
Логически все ок. 

Но очень плохо читается код ( Так как он разделен не поправилам

2022-01-24 10:09 UTC, merged