решение задач 3 модуля
js-tasks-ru/jsbasic-20220113_petrzavadski pull request #4
Opened 2022-01-29 02:00 UTC by petrzavadski

2022-01-29 02:01 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-30 12:23 UTC, SinimaWath requested changes

2022-01-30 12:23 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return (index==res.length-1) ? (r.name+', '+ r.balance) : (r.name+', '+ r.balance + '\n');
Давай вставлять `\n` через join('\n')

2022-01-30 12:23 UTC, SinimaWath commented on 3-module/5-task/index.js
> +   if (isFinite(item) && (item)) arr.push(item*1)
для преобразования в number, обычно используют:
- parseInt()
- или `+item`

2022-01-31 17:16 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-02 17:46 UTC, SinimaWath approved these changes

2022-02-02 17:46 UTC, merged